name: Flex Bison CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install apt packages
        run: sudo apt install build-essential flex bison

      - name: Make build
        run: make

      - uses: actions/upload-artifact@v4
        with:
          name: compiler
          path: compiler
          if-no-files-found: error
          
